### ISSUE TITLE
Trivy scanner ignores OPERATOR_STARBOARD_NAMESPACE

### ISSUE THREAD

**Issue by ribbybibby** [aquasecurity/starboard-operator#26]
Despite having set `OPERATOR_STARBOARD_NAMESPACE` to `example`, the operator is still trying to create jobs in the default namespace `starboard` when using the trivy scanner. 

See the `job.namespace` field here:
```
{"level":"info","ts":1596107943.1626804,"logger":"controllers.pod","msg":"Creating scan job","owner.kind":"StatefulSet","owner.name":"example","owner.namespace":"example","pod.name":"example-0","job.name":"5ece38e1-9975-44ee-8630-12367b312de5","job.namespace":"starboard"}
```

This results in errors like this when the `starboard` namespace doesn't exist:
```
"msg":"Reconciler error","controller":"pod","name":"example-0","namespace":"example","error":"namespaces \"starboard\" not found"
```

I think this is ultimately down to the fact that the namespace is hard coded in starboard: https://github.com/aquasecurity/starboard/blob/master/pkg/kube/starboard.go#L8

**Comment by avdhoot** [comment]
@lizrice @danielpacak  ^^

**Comment by danielpacak** [comment]
You're right @ribbybibby . I'm sorry for late reply but it took us a while to think about install modes that we want to support. We have the PR #37 opened to solve the problem you mentioned by setting the `OPERATOR_NAMESPACE` env. Note also that we'll have the`OPERATOR_TARGET_NAMESPACES` env to control operator's multitenancy inspired by OLM https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/operatorgroups.md

**Comment by danielpacak** [comment]
I believe this has been fixed now by one of the recent commits on the master branch.
